### ISSUE TITLE
Question: Is there an easier way to navigate trough pages?

### ISSUE THREAD

**Issue by vejandla** [octokit/plugin-enterprise-server.js#100]
I see that pagination information is coming in the headers but, do we have an API method that was built to easily navigate through pages or get all pages info in one call? 

also, any pointers to documentation to understand the API better.?

**Comment by gr2m** [comment]
For pagination, you can add this plugin:
https://github.com/octokit/plugin-paginate-rest.js

I'm very sorry about the sad state of the current docs :( I'm working on a generic setup for the current `@octokit/rest` documentation at https://octokit.github.io/rest.js/v17/.

I think what I can do at the very least is to add separate Markdown files for each endpoint, with descriptions and parameters, as we currently have at https://github.com/octokit/plugin-rest-endpoint-methods.js/tree/master/docs. Still far from perfect, but probably better than what we have today

**Comment by vejandla** [comment]
@gr2m  Thanks for looking into it and appreciate your response. but If I user the pluginPaginateRest, is n't it deceiving the purpose of using the octokit enterprise API? for example

to fetch a list of pull requests for a repo, I'm planning on using this. 

```js
octokit.pulls.list({
  owner,
  repo,
  state,
  head,
  base,
  sort,
  direction,
  per_page,
  page
});
```

but if I use the paginate plugin, don't I have to hard code the URL and deceives the purpose of the above method, is n't it?

Please correct me if I am wrong? is this the right usage or is there a different way to achieve both?

**Comment by gr2m** [comment]
you can get the request options for every endpoint method + your parameters like this:

```js
const options = octokit.pulls.list.endpoint.merge({
  owner,
  repo,
  state,
  head,
  base,
  sort,
  direction,
  per_page
});
```

Leave out the `page` option.

Then you can pass these options into the `.paginate` method

```js
octokit.paginate(options)
```

Does that work for you?

I have an item in my back log to implement 

```js
octokit.paginate(octokit.pulls.list, {
  owner,
  repo,
  state,
  head,
  base,
  sort,
  direction,
  per_page
});
```

to make the code less verbose, but it's not there yet.

**Comment by gr2m** [comment]
This should work now

```js
octokit.paginate(octokit.pulls.list, {
  owner,
  repo,
  state,
  head,
  base,
  sort,
  direction,
  per_page
});
```

Does that work for you?

**Comment by vejandla** [comment]
@gr2m yes. Thanks for the help👍🙏

**Comment by gr2m** [comment]
Glad it worked :)
