### ISSUE TITLE
Missing types for GitHub Enterprise Server 3.x

### ISSUE THREAD

**Issue by Eddman** [octokit/plugin-enterprise-server.js#362]
There is new GitHub Enterprise Server 3.x, but no types are generated in this repository.

**Comment by gr2m** [comment]
I've quite a backlog right now, but I'll get to it eventually. If you'd like to send a pull request I can review it right away, otherwise I'll have to ask you for some patience

**Comment by Eddman** [comment]
I tried :stuck_out_tongue_winking_eye: But it depends on https://github.com/gr2m/github-openapi-graphql-server and that one I'm not able to start. I have no experience with vercel.com :man_shrugging: 

I've created PR gr2m/github-openapi-graphql-server#107 to add missing constants, but I don't know how I can verify it works :man_shrugging: 

The rest I think should be simple :smile: https://github.com/octokit/plugin-enterprise-server.js/compare/master...Eddman:add_30

**Comment by Eddman** [comment]
Hmm I was able to use my Vercel app deployed by that PR bot. So PR updated with endpoints :smile: and ready for review.
