### ISSUE TITLE
npm added as a production dependency - typo?

### ISSUE THREAD

**Issue by dominykas** [octokit/plugin-enterprise-server.js#386]
Just double checking that this was intended: https://github.com/octokit/plugin-enterprise-server.js/pull/381/commits/a5cb8b595e7a85dc413a190f8db62e28f4c84e38 - since it also added `i`, I'm wondering it this was a typo `npm i npm i` or something?

**Comment by gr2m** [comment]
> npm i npm i

that is exactly what happened when I run a script against multiple repositories 🤦🏼 thanks for bringing that to our attention. Thanks for taking care of it so quickly @oscard0m @wolfy1339

**Comment by dominykas** [comment]
Thank you 🙇 

Can someone please publish this on npm?

**Comment by gr2m** [comment]
yep sorry, should have used a fix commit for that
