### ISSUE TITLE
Add GHE 3.1 and 3.2 endpoints

### ISSUE THREAD

**Issue by Eddman** [octokit/plugin-enterprise-server.js#427]
There are already GHE 3.1 and 3.2, but this plugin contains only 3.0. 

Please add missing GHE versions.

#### Note:
I tried to open a PR instead, but failed to do so. The code in this repo is not executable; I've set `VERSION` to `5.2.2`, even removed deprecated versions `220` and `221` from `ghe-versions.js`, but it is still failing on `/app/hook/config` for GHE 2.22: 
```
Cannot read property 'deprecationDate' of undefined
```
at
```typescript
    deprecationDate: definition["x-github"].deprecationDate,
```

Is there any trick to run it?

**Comment by wolfy1339** [comment]
You can take a look at this PR: https://github.com/octokit/plugin-enterprise-server.js/pull/363 as to how to add the new versions

**Comment by Eddman** [comment]
Well would be great to have any solution in the meantime 🙂Is there something I can do to help?

**Comment by Eddman** [comment]
Any news here?

**Comment by wolfy1339** [comment]
Note that @octokit has no current maintainer, subscribe to https://github.com/octokit/octokit.js/discussions/620#discussioncomment-1472174 for updates

**Comment by Eddman** [comment]
@wolfy1339 Any news on that? Is this now a non-supported library and is there a replacement? It's a shame that GH has Octokit examples in docs, but nobody takes care of it :disappointed:

**Comment by wolfy1339** [comment]
Unfortunately, I don't have any news. There still isn't an active maintainer for the JS octokit packages.

**Comment by wolfy1339** [comment]
There's now GHES 3.2 endpoints generated
