### ISSUE TITLE
[BUG]: Broken API

### ISSUE THREAD

**Issue by Eddman** [octokit/plugin-enterprise-server.js#654]
### What happened?

I upgraded to latest library version `15.2.1` and realized that some teams endpoints are missing. After some digging I realized there was a PR https://github.com/octokit/plugin-enterprise-server.js/pull/625 that removed these from all GHES versions and stated that it was due to deprecation. Now I don't understand why this happened. In `@octokit/types` the definition still exist and in GH docs for even latest GHES 3.12 there is nothing about deprecation of these APIs.

It is even a buggy update cause the [`project.deleteCard` method points to a method that removes repo from team](https://github.com/octokit/plugin-enterprise-server.js/pull/625/files#diff-1ac1b01d016e566072633b97b1a87eebeb125b0a6c40088ddf6fe1379078be71R35532).

### Versions

plugin-enterprise-server.js@15.2

### Relevant log output

```shell
TypeError: Failed to add team @<my team slug> to list of repository collaborators in repository `<my repo>`.

Original error: t.teams.addOrUpdateRepoPermissionsInOrg is not a function
    at /home/bot/bot.cjs:525:61736
    at /home/bot/bot.cjs:1:2852064
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
The `teams.addOrUpdateRepoPermissionsInOrg` method is present in the latest version
The `projects.deleteCard` methods is pointing to the proper endpoint in the latest version

Is there any specific endpoint that is missing?

**Comment by Eddman** [comment]
Seems to have all the methods I use. Thanks!
