### ISSUE TITLE
404 Malformed URL

### ISSUE THREAD

**Issue by purimetla** [octokit/plugin-enterprise-server.js#95]
While trying to call get Orgs endpoint as per the documentation, internally it's not forming right url.

This is the URL that being called internally : `https://github.companyurl.com/api/v3orgname` when I execute the below code. Please advise.

```js
const { Octokit } = require("@octokit/core");
const {
  enterpriseServer219
} = require("@octokit/plugin-enterprise-server");


const OctokitEnterprise = Octokit.plugin(enterpriseServer219);
const octokit = new OctokitEnterprise({
  auth: "secret123",
  baseUrl: "https://github.companyurl.com/api/v3"
});

octokit.orgs.get("orgname").then(function(response){
 console.log(response)
}, (error) => {
  console.log(error);
});
```

**Comment by gr2m** [comment]
Thanks for reporting the issue! You should be able to resolve it by adding a trailing `/` to your baseUrl.

```diff
  const octokit = new OctokitEnterprise({
    auth: "secret123",
-   baseUrl: "https://github.companyurl.com/api/v3"
+   baseUrl: "https://github.companyurl.com/api/v3/"
  });
```

But I agree that the the `baseUrl` option should be normalized automatically. I thought it was 🤷‍♂  it probably broke at some point and I didn't have a test for it. I'll look into it

**Comment by gr2m** [comment]
Sorry never-mind my previous comment, I've misread your issue.

I was not able to reproduce your error. I've created a test case here, but everything seems to work as expected https://github.com/octokit/plugin-enterprise-server.js/pull/96/files#diff-6b0be7ebc66af827d76f277947f86631R35-R55

How do you know that the request is sent to https://github.companyurl.com/api/v3orgname?

**Comment by vejandla** [comment]
@gr2m looks like @purimetla is passing a string and in your test, you are passing an object.

the URL seems to be logged in the catch block error message (as one of the headers)

As per the [Markdown](https://github.com/octokit/plugin-enterprise-server.js/blob/master/docs/ghe-219.md#others), the method is accepting the org and it seems little confusing whether to pass object or string?  Are they any examples where we can look into understanding the API better.

**Comment by gr2m** [comment]
Oh I see, thank you @vejandla ! Yes these docs are horrible, my apologies. You always pass an object. I'll fix these docs to at least have `{}` braces around the arguments

**Comment by purimetla** [comment]
Thanks @gr2m and @vejandla, appreciate it!
